language: python
sudo: false

python: "3.6"
node_js: "10"
ruby: "2.6"

cache:
  pip: true

install:
  - pip install -r requirements.txt
  - bundle install

script:
  - bundle exec jekyll build
  - ./build.sh
  - cp -R _site/. site/

deploy:
 provider: pages
 skip_cleanup: true
 github_token: $GH_TOKEN
 local_dir: site
 on:
   branch: master